export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';

export const ADD_ITEMS_REQUEST = 'ADD_ITEMS_REQUEST';
export const ADD_ITEMS_SUCCESS = 'ADD_ITEMS_SUCCESS';
export const ADD_ITEMS_FAILURE = 'ADD_ITEMS_FAILURE';

export const EDIT_ITEMS_REQUEST = 'EDIT_ITEMS_REQUEST';
export const EDIT_ITEMS_SUCCESS = 'EDIT_ITEMS_SUCCESS';
export const EDIT_ITEMS_FAILURE = 'EDIT_ITEMS_FAILURE';

export const DELETE_ITEMS_REQUEST = 'DELETE_ITEMS_REQUEST';
export const DELETE_ITEMS_SUCCESS = 'DELETE_ITEMS_SUCCESS';
export const DELETE_ITEMS_FAILURE = 'DELETE_ITEMS_FAILURE';